"""add relationships

Revision ID: 0293f740edba
Revises: 544e83c7a134
Create Date: 2024-08-07 22:43:42.734960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0293f740edba'
down_revision: Union[str, None] = '544e83c7a134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_info', sa.Column('product_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products_info', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_info', type_='foreignkey')
    op.drop_column('products_info', 'product_id')
    # ### end Alembic commands ###
