"""add price and labet to the product

Revision ID: 0a676924c9e8
Revises: da89275c03fd
Create Date: 2024-09-24 21:00:25.985427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a676924c9e8'
down_revision: Union[str, None] = 'da89275c03fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('label', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'label')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
