"""add privacy policy and user agreement

Revision ID: 6942c8501818
Revises: be6e8cbab5ed
Create Date: 2024-10-07 10:58:45.419111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6942c8501818'
down_revision: Union[str, None] = 'be6e8cbab5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('privacy_policy', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('user_agreement', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_content', 'user_agreement')
    op.drop_column('main_content', 'privacy_policy')
    # ### end Alembic commands ###
