"""to transfer text pages into one entity

Revision ID: 1b2e2156ed2c
Revises: 6942c8501818
Create Date: 2024-10-10 07:51:09.074859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b2e2156ed2c'
down_revision: Union[str, None] = '6942c8501818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_pages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('our_contacts', sa.String(), nullable=True),
        sa.Column('delivery_and_payment', sa.String(), nullable=True),
        sa.Column('privacy_policy', sa.String(), nullable=True),
        sa.Column('user_agreement', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('main_content', sa.Column('address', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('link_to_the_map', sa.String(), nullable=True))
    op.drop_column('main_content', 'one_news_title')
    op.drop_column('main_content', 'privacy_policy')
    op.drop_column('main_content', 'product_title')
    op.drop_column('main_content', 'user_agreement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('user_agreement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('main_content', sa.Column('product_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('main_content', sa.Column('privacy_policy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('main_content', sa.Column('one_news_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('main_content', 'link_to_the_map')
    op.drop_column('main_content', 'address')
    op.drop_table('text_pages')
    # ### end Alembic commands ###
