"""remove footer

Revision ID: 14dbf9f7c611
Revises: c063a779885f
Create Date: 2024-10-21 05:29:32.135926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14dbf9f7c611'
down_revision: Union[str, None] = 'c063a779885f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_content', 'footer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('footer', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
