"""change characteristics table

Revision ID: 34e1e1bbd8fd
Revises: 3590c054ee67
Create Date: 2024-08-08 16:04:28.780464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e1e1bbd8fd'
down_revision: Union[str, None] = '3590c054ee67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name_of_characteristic', sa.String(), nullable=False),
    sa.Column('value_of_characteristic', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('products_characteristics')
    op.add_column('products', sa.Column('image_name', sa.String(), nullable=False, server_default="coming_soon.png"))
    op.drop_column('products', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'image_name')
    op.create_table('products_characteristics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lifting_capacity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body_volume', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_axes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suspension_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weight_without_load', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('axle_brand', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_brakes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ssu_height', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('internal_dimensions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('specifications_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_TS', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('engine_volume', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_of_fuel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_characteristics_pkey')
    )
    op.drop_table('products_info')
    # ### end Alembic commands ###
