"""empty message

Revision ID: 71a4be555332
Revises: 
Create Date: 2024-08-08 21:31:51.183332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a4be555332'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('image_name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True, server_default="true"),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_info',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('name_of_characteristic', sa.String(), nullable=False),
        sa.Column('value_of_characteristic', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_info')
    op.drop_table('products')
    # ### end Alembic commands ###
