"""add fields to fill with content

Revision ID: 8b0e0ab63b98
Revises: 34e1e1bbd8fd
Create Date: 2024-08-21 10:45:04.669702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0e0ab63b98'
down_revision: Union[str, None] = '34e1e1bbd8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_content',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('logo', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('main_urls', sa.String(), nullable=True),
        sa.Column('main_title', sa.String(), nullable=True),
        sa.Column('main_desc', sa.String(), nullable=True),
        sa.Column('products_title', sa.String(), nullable=True),
        sa.Column('product_title', sa.String(), nullable=True),
        sa.Column('footer', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_content')
    # ### end Alembic commands ###
