"""add cascade delete

Revision ID: ec65a2532187
Revises: 7ad3e1c1b0e4
Create Date: 2024-08-25 22:34:09.752951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec65a2532187'
down_revision: Union[str, None] = '7ad3e1c1b0e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('products_info_product_id_fkey', 'products_info', type_='foreignkey')
    op.create_foreign_key(None, 'products_info', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_info', type_='foreignkey')
    op.create_foreign_key('products_info_product_id_fkey', 'products_info', 'products', ['product_id'], ['id'])
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
