"""remove urls

Revision ID: 26ad7769c036
Revises: 8b0e0ab63b98
Create Date: 2024-08-21 11:50:48.938550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ad7769c036'
down_revision: Union[str, None] = '8b0e0ab63b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_content', 'main_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('main_urls', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
