"""add the about us section

Revision ID: 749d5a75ecc8
Revises: ec65a2532187
Create Date: 2024-09-02 15:20:23.572885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749d5a75ecc8'
down_revision: Union[str, None] = 'ec65a2532187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('header_title', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('header_desc', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('amout_us_image', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('amout_us_title', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('amout_us_desc', sa.String(), nullable=True))
    op.drop_column('main_content', 'main_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('main_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('main_content', 'amout_us_desc')
    op.drop_column('main_content', 'amout_us_title')
    op.drop_column('main_content', 'amout_us_image')
    op.drop_column('main_content', 'header_desc')
    op.drop_column('main_content', 'header_title')
    # ### end Alembic commands ###
