"""add the about us section

Revision ID: 86e65287cac1
Revises: ec65a2532187
Create Date: 2024-09-06 09:46:01.784801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e65287cac1'
down_revision: Union[str, None] = 'ec65a2532187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('header_title', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('header_desc', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('about_us_image', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('about_us_title', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('about_us_desc', sa.String(), nullable=True))
    op.drop_column('main_content', 'main_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('main_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('main_content', 'about_us_desc')
    op.drop_column('main_content', 'about_us_title')
    op.drop_column('main_content', 'about_us_image')
    op.drop_column('main_content', 'header_desc')
    op.drop_column('main_content', 'header_title')
    # ### end Alembic commands ###
