"""add new column in Products

Revision ID: 71a4be555332
Revises: 1d16afb03eab
Create Date: 2024-07-25 22:21:00.374986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a4be555332'
down_revision: Union[str, None] = '1d16afb03eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('products', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('model', sa.String(), nullable=True))
    op.add_column('products', sa.Column('target', sa.String(), nullable=True))
    op.add_column('products', sa.Column('lifting_capacity', sa.String(), nullable=True))
    op.add_column('products', sa.Column('body_volume', sa.String(), nullable=True))
    op.add_column('products', sa.Column('number_of_axes', sa.String(), nullable=True))
    op.add_column('products', sa.Column('suspension_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('weight_without_load', sa.String(), nullable=True))
    op.add_column('products', sa.Column('axle_brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('type_of_brakes', sa.String(), nullable=True))
    op.add_column('products', sa.Column('ssu_height', sa.String(), nullable=True))
    op.add_column('products', sa.Column('internal_dimensions', sa.String(), nullable=True))
    op.add_column('products', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('products', sa.Column('specifications_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('country', sa.String(), nullable=True))
    op.add_column('products', sa.Column('type_of_TS', sa.String(), nullable=True))
    op.add_column('products', sa.Column('engine_volume', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('type_of_fuel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'type_of_fuel')
    op.drop_column('products', 'engine_volume')
    op.drop_column('products', 'type_of_TS')
    op.drop_column('products', 'country')
    op.drop_column('products', 'specifications_id')
    op.drop_column('products', 'phone')
    op.drop_column('products', 'internal_dimensions')
    op.drop_column('products', 'ssu_height')
    op.drop_column('products', 'type_of_brakes')
    op.drop_column('products', 'axle_brand')
    op.drop_column('products', 'weight_without_load')
    op.drop_column('products', 'suspension_type')
    op.drop_column('products', 'number_of_axes')
    op.drop_column('products', 'body_volume')
    op.drop_column('products', 'lifting_capacity')
    op.drop_column('products', 'target')
    op.drop_column('products', 'model')
    op.drop_column('products', 'year')
    op.drop_column('products', 'condition')
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
