"""change type, add field

Revision ID: 884b3bccd71e
Revises: 822dcd1205e8
Create Date: 2024-09-11 22:14:26.938782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '884b3bccd71e'
down_revision: Union[str, None] = '822dcd1205e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title', sa.String(), nullable=True))
    op.add_column('news', sa.Column('news_image_name', sa.String(), nullable=True))
    op.alter_column('news', 'date_of_the_news',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('news', 'name')
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'image_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('news', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('news', 'date_of_the_news',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('news', 'news_image_name')
    op.drop_column('news', 'title')
    # ### end Alembic commands ###
