"""add new titles

Revision ID: da89275c03fd
Revises: 884b3bccd71e
Create Date: 2024-09-13 10:58:33.536467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da89275c03fd'
down_revision: Union[str, None] = '884b3bccd71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_content', sa.Column('news_title', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('one_news_title', sa.String(), nullable=True))
    op.add_column('main_content', sa.Column('brands_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_content', 'brands_title')
    op.drop_column('main_content', 'one_news_title')
    op.drop_column('main_content', 'news_title')
    # ### end Alembic commands ###
