networks:
  dev:


services:
  nginx:
    build:
      context: .
      dockerfile: "Dockerfile.nginx"
    container_name: ruverauto_nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ruverauto
    links:
      - ruverauto
    networks:
      - dev

  db:
    image: postgres:15
    container_name: ruverauto_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 2345:5432
    networks:
      - dev

  ruverauto:
    image: ruverauto
    build:
      context: .
    container_name: ruverauto
    volumes:
      - /home/RuverAuto/app/static/images:/ruverauto/app/static/images
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["/ruverauto/docker/app.sh"]
    # ports:
      # - 8080:8000
    networks:
      - dev

volumes:
  postgresdata:
