services:
  nginx:
    build:
      context: .
      dockerfile: "Dockerfile.nginx"
    container_name: ruverauto_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - ruverauto
    networks:
      - prod

  db:
    image: postgres:15
    container_name: ruverauto_db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 2345:5432
    networks:
      - dev

  ruverauto:
    image: ruverauto
    build:
      context: .
    container_name: ruverauto
    volumes:
      - static_volume:/ruverauto/app/static/images
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["/ruverauto/docker/app.sh"]
    expose:
      - "8000"
    networks:
      - prod

volumes:
  postgresdata:
  static_volume:
  static:

networks:
  prod:
