FROM nginx:1.24.0
COPY nginx.conf /etc/nginx/nginx.conf
COPY ruverauto.ru.crt /etc/ssl/ruverauto.ru.crt
COPY ruverauto.ru.key /etc/ssl/ruverauto.ru.key
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]