column_labels = {
    "brand": "Марка",
    "condition": "Состояние",
    "year": "Год выпуска",
    "model": "Модель",
    "target": "Назначение",
    "lifting_capacity": "Грузоподьемность, кг.",
    "body_volume": "Объеи кузова, куб. м.",
    "number_of_axes": "Количество осей",
    "suspension_type": "Тип подвески",
    "weight_without_load": "Масса без нагрузки, кг.",
    "axle_brand": "Марка осей",
    "type_of_brakes": "Тип тормозов",
    "ssu_height": "Высота ССУ, мм.",
    "internal_dimensions": "Внутренние габариты, мм.",
    "phone": "Телефон",
    "specifications_id": "Спецификация",
    "country": "Страна",
    "type_of_TS": "Тип ТС",
    "engine_volume": "Объем двигателя",
    "type_of_fuel": "Тип топлива",
    "image_id": "Фото",
}
